### ISSUE TITLE
can't install via pip - dependency problem

### ISSUE THREAD

**Issue by jmcclelland** [riccardoFasan/deeply#2]
I'm trying to install on a debian testing machine and I'm getting this error:

```
0 jamie@liberace:~$ pip install deeply-translator
ERROR: Could not find a version that satisfies the requirement deeply-translator
ERROR: No matching distribution found for deeply-translator
1 jamie@liberace:~$ 
```

Any suggestions?

Thanks!

**Comment by jmcclelland** [comment]
Oh, I see, `deeply` requires python >= 3.10 and I have 3.9. Hm. Is there any way to make it work with an older version of python?

**Comment by riccardoFasan** [comment]
Hi. I discovered this problem with pip some days ago, but I didn't have time to solve it.
Deeply should also work with versions older than 3.10.
I will do my best to fix and lower the minimum required python version in the next few days.
If you don't want to wait for the fix, you could download the source and run deeply manually in the meantime.

**Comment by jmcclelland** [comment]
Thanks! And yes, I just tried that and it seems to work propelry with python 3.9. Thanks for this great tool!
